// THESE ARE DEFAULT VALUES AFFECTING APP DISPLAY AND FUNCTIONALITY
// CHANGES IN APP ARE **NOT** REFLECTED HERE AND ARE NOT APPLIED AFTER QUITTING

export const BOOLEAN_VALUES = {
    DEVELOPER_MODE: true,
    SHOW_ITEM_INPUT: false,
    SHOW_GENERATE_ROUTE_BUTTON: false,
    SHOW_AISLES: false,
    SHOW_HOME_TAB: true,
    SHOW_SETTINGS_TAB: true,
    SHOW_NOTIFICATIONS_TOGGLE: false,
};

export const USR_INPT_CHAR_LMT = 200;
